#!/bin/bash

SUFFIX="lulesh"
MAX_POL=1
PROC_BIND="close"
PLACES=cores
WAIT_POL="active"
APOLLO_PERIOD=10000
THREAD_CAP=36
POLICY="Random"

APOLLO_TRACE_CSV_FOLDER_SUFFIX="-$SUFFIX" \
APOLLO_COLLECTIVE_TRAINING=0 \
APOLLO_LOCAL_TRAINING=1 \
OMP_NUM_THREADS=$THREAD_CAP \
OMP_WAIT_POLICY=$WAIT_POL \
APOLLO_RETRAIN_ENABLE=0 \
APOLLO_INIT_MODEL=$POLICY \
APOLLO_GLOBAL_TRAIN_PERIOD=$APOLLO_PERIOD \
APOLLO_STORE_MODELS=0 \
APOLLO_TRACE_CSV=1 \
OMP_PROC_BIND=$PROC_BIND \
OMP_PLACES=$PLACES \
APOLLO_ENABLE_PERF_CNTRS=1 \
srun -n1 -N1 --export=ALL ./lulesh2.0 -s 30 -r 100 -b 0 -c 0 -i 1000

#gdb -e ./lulesh2.0 -ex "r -s 30 -r 100 -b 0 -c 0 -i 1000"


