#!/bin/bash

export APOLLO_COLLECTIVE_TRAINING=0
export APOLLO_LOCAL_TRAINING=1
#export APOLLO_SINGLE_MODEL=1
export APOLLO_SINGLE_MODEL=0
export APOLLO_REGION_MODEL=1
#export APOLLO_STORE_MODELS=1
export APOLLO_STORE_MODELS=0
#export APOLLO_TRACE_MEASURES=1
export APOLLO_TRACE_MEASURES=0
export APOLLO_TRACE_CSV=0
#export OMP_WAIT_POLICY=passive
export OMP_WAIT_POLICY=active
export OMP_PROC_BIND=true
#export OMP_PROC_BIND=false
export OMP_PLACES=cores
export OMP_NESTED=true

EXEC_DIR=~/workspace/lulesh/build
echo $EXEC_DIR
cd $EXEC_DIR

PROB_SIZE="-s 60"
NUM_ITERS="-i 100"
NUM_REGIONS="-r 100"

export OMP_NUM_THREADS=36
$EXEC_DIR/./lulesh2.0 $PROB_SIZE $NUM_ITERS $NUM_REGIONS

export OMP_NUM_THREADS=1
$EXEC_DIR/./lulesh2.0 $PROB_SIZE $NUM_ITERS $NUM_REGIONS